spring:
  rabbitmq:
    host: 192.168.189.139
    username: admin
    password: admin
    #虚拟主机
    virtual-host: /
    #端口
    port: 5672
    listener:
      simple:
        #消费者的最小数量
        concurrency: 10
        #限制消费者每次只处理一条消息，处理完毕再继续下一条
        prefetch: 1
        #启动时是否默认启动容器，默认为true
        auto-startup: true
        #当你的消息被拒绝的时候重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试，默认为false
        enabled: true
        #重试时间
        initial-interval: 1000ms
        #重试最大次数，默认3次
        max-attempts: 3
        #重试最大时间
        max-interval: 10000ms
        #重试间隔时间的倍数
        multiplier: 1
  resources:
    cache:
      cachecontrol:
        max-age: 3600
    add-mappings: true
    chain:
      cache: true
      enabled: true
      compressed: true
      html-application-cache: true
    static-locations: classpath:/static/
  thymeleaf:
    cache: false
    content-type: text/html
    mode: HTML
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    password: 12345678
    hikari:
      pool-name: DataHikariCP
      minimum-idle: 5
      idle-timeout: 1800000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: 192.168.189.139
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        max-idle: 200
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.yun.seckilldemo.pojo

logging:
  level:
    com.yun.seckilldemo.mapper: debug
server:
  port: 8081
